<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Delviana Pasaribu">
<meta name="dcterms.date" content="2024-12-31">

<title>Pengaruh Ekspor Emas terhadap GDP Indonesia Tahun 2012 hingga 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Emas terhadap GDP Indonesia Tahun 2012 hingga 2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Delviana Pasaribu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 31, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo</figcaption>
</figure>
</div>
<style>
p {text-align: justify;}
</style>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Ekspor emas telah menjadi salah satu komponen penting dalam perekonomian Indonesia, memberikan kontribusi signifikan terhadap Produk Domestik Bruto (GDP). Indonesia berkembang menjadi salah satu produsen dan eksportir emas terbesar di dunia, menempati posisi strategis di kawasan ASEAN. Peran emas dalam ekonomi Indonesia sangat luas, mulai dari digunakan sebagai alat investasi, cadangan devisa, hingga standar keuangan. Selain itu, emas juga menyediakan sumber pendapatan devisa yang substansial bagi negara.Tren positif ekspor emas Indonesia terlihat jelas dengan kontribusi yang signifikan terhadap total nilai ekspornya. Produk emas bahkan menjadi penyumbang terbesar kedua setelah minyak dan gas, menunjukkan betapa besar perannya dalam struktur perdagangan nasional. Dengan demikian, sektor emas bukan hanya sekadar sumber pendapatan devisa, tetapi juga sebagai pendorong pertumbuhan ekonomi secara lebih luas.</p>
<p>Ekspor memiliki dampak langsung terhadap GDP melalui peningkatan penerimaan negara. Proporsi komponen ekspor dalam perhitungan GDP mengalami peningkatan dari waktu ke waktu, mencerminkan kontribusi signifikan dari sektor ini terhadap pertumbuhan ekonomi. Kenaikan permintaan global untuk emas, terutama dari negara-negara seperti Singapura dan Hong Kong, turut mendorong daya saing produk emas Indonesia agar lebih tinggi. Namun, ada beberapa faktor yang mempengaruhi ekspor emas Indonesia. Kondisi ekonomi global, permintaan pasar internasional, dan daya saing produk merupakan aspek yang harus dipertimbangkan. Analisis menggunakan metode Revealed Comparative Advantage (RCA) menunjukkan bahwa produk emas Indonesia memiliki daya saing yang baik di pasar global, terutama di negara-negara tujuan utama seperti Singapura dan Australia. Meskipun begitu, masih ada tantangan di pasar Jepang di mana daya saing produk emas Indonesia relatif rendah.</p>
<p>Dari analisis tersebut, dapat disimpulkan bahwa ekspor emas memiliki pengaruh yang signifikan terhadap GDP Indonesia. Untuk memaksimalkan potensi pertumbuhan ekonomi melalui sektor ini, transformasi kebijakan dan peningkatan infrastruktur serta sumber daya manusia menjadi kunci. Dengan strategi yang tepat, diharapkan kontribusi sektor emas terhadap perekonomian nasional akan semakin meningkat seiring dengan perkembangan pasar global. Oleh karena itu, penting bagi pemerintah dan industri terkait untuk terus memantau dan meningkatkan efektivitas operasional sehingga bisa menjawab tuntutan pasar dan meningkatkan nilai tambah nasional.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penulis dalam penelitian ini mengumpulkan data ekspor emas melalui laporan tahunan Badan Pusat Statistik (BPS) Indonesia untuk periode 2012 hingga 2023. Selain itu, data Produk Domestik Bruto (GDP) Indonesia diperoleh dari sumber internasional seperti World Bank. Penelitian ini menggunakan dua variabel, yaitu variabel X (ekspor emas) dan variabel Y (GDP Indonesia). Data yang digunakan bersifat time series dan mencakup periode 2012 hingga 2023.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Penelitian ini akan menjawab persoalan mengenai:</p>
<ol type="1">
<li>Seberapa besar kontribusi ekspor emas terhadap pertumbuhan GDP Indonesia?</li>
<li>Apa saja faktor yang mempengaruhi ekspor emas Indonesia di pasar internasional?</li>
<li>Bagaimana daya saing produk emas Indonesia dibandingkan dengan negara eksportir lainnya?</li>
<li>Apa tantangan yang dihadapi Indonesia dalam mempertahankan posisi sebagai eksportir emas?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini dirumuskan untuk memberikan manfaat bagi pemerintah dan masyarakat, dengan fokus pada pengembangan sektor ekspor emas dan dampaknya terhadap perekonomian Indonesia:</p>
<p><em>1. Bagi Pemerintah</em> Memberikan rekomendasi kebijakan yang berbasis data untuk meningkatkan kinerja ekspor emas dan kontribusinya terhadap GDP Indonesia. Mengidentifikasi strategi yang dapat digunakan pemerintah untuk mengoptimalkan pemanfaatan sumber daya emas, sehingga dapat mendukung pertumbuhan ekonomi yang berkelanjutan.</p>
<p><em>2. Bagi Masyarakat</em> Meningkatkan kesadaran publik mengenai peran ekspor emas dalam perekonomian nasional dan dampaknya terhadap kesejahteraan masyarakat. Mendorong partisipasi masyarakat dalam proses pengambilan keputusan terkait kebijakan energi dan pertambangan, dengan memahami implikasi dari kebijakan tersebut terhadap kehidupan sehari-hari mereka.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Penelitian ini membahas berbagai aspek terkait ekspor emas Indonesia, dengan fokus pada kontribusinya terhadap pertumbuhan GDP, faktor-faktor yang mempengaruhi ekspor, daya saing produk emas, dan tantangan yang dihadapi dalam mempertahankan posisi sebagai eksportir. Ekspor emas telah menjadi salah satu komponen penting dalam perekonomian Indonesia, di mana Indonesia dikenal sebagai salah satu produsen dan eksportir emas terbesar di dunia. Data dari Badan Pusat Statistik menunjukkan bahwa ekspor logam mulia dan perhiasan mengalami tren penguatan yang sejalan dengan peningkatan harga emas di pasar internasional. Hal ini mencerminkan potensi besar sektor emas dalam memberikan kontribusi signifikan terhadap nilai ekspor nasional.</p>
<p>Fluktuasi harga emas di pasar global menjadi faktor kunci yang mempengaruhi kinerja ekspor emas Indonesia. Penelitian menunjukkan bahwa ketidakpastian harga dapat memengaruhi keputusan investasi dan produksi di sektor ini, serta berdampak pada pendapatan negara. Kontrak jangka panjang sering kali diadopsi sebagai strategi untuk menjamin stabilitas pendapatan, meskipun ada risiko terkait fluktuasi harga pasar. Selain itu, analisis daya saing produk emas Indonesia menggunakan metode Revealed Comparative Advantage (RCA) menunjukkan bahwa produk emas Indonesia memiliki daya saing yang baik di pasar global, terutama di negara-negara tujuan utama seperti Singapura dan Australia. Namun, tantangan tetap ada, terutama di pasar Jepang di mana daya saing produk emas Indonesia relatif rendah.</p>
<p>Faktor-faktor yang mempengaruhi ekspor emas mencakup kondisi ekonomi global, permintaan pasar internasional, serta kebijakan perdagangan yang diterapkan oleh pemerintah. Penelitian sebelumnya mengindikasikan bahwa GDP per kapita negara tujuan ekspor memiliki pengaruh signifikan terhadap permintaan ekspor emas Indonesia. Oleh karena itu, penting bagi pemerintah untuk terus memantau dan menyesuaikan kebijakan perdagangan guna meningkatkan daya saing produk emas.Tantangan lain yang dihadapi Indonesia dalam mempertahankan posisinya sebagai eksportir emas meliputi keterbatasan infrastruktur dan distribusi. Infrastruktur yang ada saat ini masih sangat terbatas, sehingga distribusi produk tidak merata di berbagai wilayah. Keterbatasan ini menyulitkan pemenuhan kebutuhan domestik dan menghambat potensi ekspor. Untuk mengatasi tantangan ini, pemerintah perlu meningkatkan investasi dalam infrastruktur dan mendukung pengembangan industri terkait.</p>
<p>Secara keseluruhan, penelitian ini menyoroti pentingnya memahami dinamika pasar emas serta tantangan yang dihadapi Indonesia dalam mempertahankan posisinya sebagai eksportir. Penelitian lebih lanjut diperlukan untuk mengeksplorasi strategi yang dapat meningkatkan daya saing sektor emas Indonesia sambil memastikan keberlanjutan pasokan energi bagi masyarakat domestik. Dengan demikian, rekomendasi kebijakan berbasis data dapat membantu meningkatkan kinerja ekspor emas dan kontribusinya terhadap pertumbuhan ekonomi nasional.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>penelitian ini menggunakan data time series yang diperoleh dari Badan Pusat Statistik dan Worldbank dalam kurun waktu 2012 hingga 2023, dan didapatkan data sebagai berikut:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>Ekspor Emas</th>
<th>GDP Indonesia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2012</td>
<td>$179,322.70</td>
<td>$917869913332.649</td>
</tr>
<tr class="even">
<td>2013</td>
<td>$202,011.40</td>
<td>$912524136718.018</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>$2,143,486.20</td>
<td>$890814755533.537</td>
</tr>
<tr class="even">
<td>2015</td>
<td>$3,319,933.40</td>
<td>$860854232686.214</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>$4,148,902.40</td>
<td>$931877364037.698</td>
</tr>
<tr class="even">
<td>2017</td>
<td>$2,700,392.50</td>
<td>$1015618744159.73</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>$2,050,413.30</td>
<td>$1042271532988.63</td>
</tr>
<tr class="even">
<td>2019</td>
<td>$1,957,708.50</td>
<td>$1119099871350.2</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>$1,468,661.50</td>
<td>$1059054842698.48</td>
</tr>
<tr class="even">
<td>2021</td>
<td>$2,585,627.90</td>
<td>$1186509691086.73</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>$3,817,525.40</td>
<td>$1319076267310.16</td>
</tr>
<tr class="even">
<td>2023</td>
<td>$5,607,131.20</td>
<td>$1371171152331.16</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/metopendelviana"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datadelviana <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"datadelviana.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>datadelviana,Y<span class="sc">~</span>X)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = datadelviana)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.400e+11 -7.060e+10  1.248e+10  1.079e+11  1.881e+11 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 9.002e+11  8.192e+10  10.988 6.66e-07 ***
X           6.045e+04  2.795e+04   2.163   0.0559 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.457e+11 on 10 degrees of freedom
Multiple R-squared:  0.3187,    Adjusted R-squared:  0.2505 
F-statistic: 4.677 on 1 and 10 DF,  p-value: 0.05586</code></pre>
</div>
</div>
<p><em>Plot Pengaruh Error Terhadap GDP</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>datadelviana<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(datadelviana<span class="sc">$</span>Y,datadelviana<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"GDP"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'blue'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot menunjukkan pola residual terhadap GDP. Terdapat tren yang dapat dilihat (peningkatan residual dengan nilai GDP), yang menunjukkan kemungkinan pelanggaran asumsi homogenitas varians (heteroskedastisitas).</p>
<p><em>Plot Pengaruh Error Terhadap GDP</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>datadelviana<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(datadelviana<span class="sc">$</span>X,datadelviana<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Ekspor Emas"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'red'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot menunjukkan distribusi residual terhadap variabel bebas (X). Residual tersebar secara acak tanpa pola tertentu, tetapi terdapat outlier yang signifikan (residual besar). Hal ini menunjukkan bahwa model mungkin tidak sepenuhnya sesuai untuk menjelaskan hubungan antara ekspor emas dan GDP.</p>
<p>Maka Saya perlu melakukan uji formal, seperti Breusch-Pagan Test, untuk memastikan keberadaan heteroskedastisitas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg2
BP = 4.5427, df = 1, p-value = 0.03306</code></pre>
</div>
</div>
<p>Hasil uji Studentized Breusch-Pagan menunjukkan nilai BP sebesar 4.5427 dengan p-value 0.03306. Karena p-value lebih kecil dari 0.05, saya menolak hipotesis nol dan menyimpulkan bahwa terdapat heteroskedastisitas dalam model. Untuk mengatasinya, saya mencoba melakukan transformasi data sebagai berikut :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>datadelviana<span class="sc">$</span>log_Y <span class="ot">&lt;-</span> <span class="fu">log</span>(datadelviana<span class="sc">$</span>Y)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>datadelviana<span class="sc">$</span>log_X <span class="ot">&lt;-</span> <span class="fu">log</span>(datadelviana<span class="sc">$</span>X)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>log_datadelviana <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Y <span class="sc">~</span> log_X, <span class="at">data =</span> datadelviana)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_datadelviana)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Y ~ log_X, data = datadelviana)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23055 -0.08028  0.01674  0.07628  0.20083 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 26.73440    0.56267  47.513 4.11e-13 ***
log_X        0.06509    0.03901   1.669    0.126    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1429 on 10 degrees of freedom
Multiple R-squared:  0.2178,    Adjusted R-squared:  0.1396 
F-statistic: 2.784 on 1 and 10 DF,  p-value: 0.1261</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(log_datadelviana), <span class="fu">resid</span>(log_datadelviana), <span class="at">main =</span> <span class="st">"Residuals vs Fitted"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>datadelviana<span class="ot">&lt;-</span> datadelviana<span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>X, <span class="sc">-</span>Y)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(datadelviana)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">TAHUN</th>
<th style="text-align: right;">m</th>
<th style="text-align: right;">log_Y</th>
<th style="text-align: right;">log_X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">6834060892</td>
<td style="text-align: right;">27.54532</td>
<td style="text-align: right;">12.09694</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">116797308</td>
<td style="text-align: right;">27.53948</td>
<td style="text-align: right;">12.21608</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">-138950889550</td>
<td style="text-align: right;">27.51540</td>
<td style="text-align: right;">14.57794</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">-240025315140</td>
<td style="text-align: right;">27.48119</td>
<td style="text-align: right;">15.01546</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">-219111717683</td>
<td style="text-align: right;">27.56047</td>
<td style="text-align: right;">15.23835</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">-47810783549</td>
<td style="text-align: right;">27.64652</td>
<td style="text-align: right;">14.80891</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">18131960337</td>
<td style="text-align: right;">27.67242</td>
<td style="text-align: right;">14.53355</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">100564120213</td>
<td style="text-align: right;">27.74355</td>
<td style="text-align: right;">14.48729</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">70081013928</td>
<td style="text-align: right;">27.68840</td>
<td style="text-align: right;">14.19986</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">130017456104</td>
<td style="text-align: right;">27.80204</td>
<td style="text-align: right;">14.76548</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">188118268794</td>
<td style="text-align: right;">27.90795</td>
<td style="text-align: right;">15.15511</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">132035028345</td>
<td style="text-align: right;">27.94669</td>
<td style="text-align: right;">15.53955</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">resid</span>(log_datadelviana))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(log_datadelviana)
W = 0.95131, p-value = 0.6562</code></pre>
</div>
</div>
<p>Berdasarkan hasil uji normalitas Shapiro-Wilk, nilai W sebesar 0.95131 dengan p-value 0.6562. Karena p-value jauh lebih besar dari tingkat signifikansi 0.05, saya tidak memiliki cukup bukti untuk menolak hipotesis nol, yang menyatakan bahwa data residual berdistribusi normal. Dengan demikian, saya dapat menyimpulkan bahwa residual dari model yang telah ditransformasi log berdistribusi normal. Hal ini menunjukkan bahwa asumsi normalitas residual dalam analisis regresi telah terpenuhi, sehingga model dapat diandalkan untuk analisis statistik lebih lanjut.</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara Ekspor Emas dan GDP. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah GDP dan <span class="math inline">\(x_t\)</span> adalah Ekspor Emas.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Regresi yang telah dilakukan, menghasilkan data sebgai berikut:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>variable</th>
<th>Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>26.73440</td>
</tr>
<tr class="even">
<td>X</td>
<td>0.06509</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>0.1261</td>
</tr>
<tr class="even">
<td>Multiple R-squared</td>
<td>0.2178</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.1396</td>
</tr>
</tbody>
</table>
<p>Didapatkan metode regresi univariat sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\ (26.73440) + \ (0.06509)+\mu_t
\]</span> Ini berarti bahwa ketika ekspor emas meningkat sebesar 1 unit (X), Produk Domestik Bruto (GDP) Indonesia (Y) diperkirakan meningkat sebesar 0.06509 dengan konstanta 26.73440.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Y <span class="sc">~</span> log_X, <span class="at">data =</span> datadelviana)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Y ~ log_X, data = datadelviana)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23055 -0.08028  0.01674  0.07628  0.20083 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 26.73440    0.56267  47.513 4.11e-13 ***
log_X        0.06509    0.03901   1.669    0.126    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1429 on 10 degrees of freedom
Multiple R-squared:  0.2178,    Adjusted R-squared:  0.1396 
F-statistic: 2.784 on 1 and 10 DF,  p-value: 0.1261</code></pre>
</div>
</div>
<p>Intersep(B0) sebesar 26.73440 dengan p-value &lt;0,001 yang artinya sangat signifikan secara statistik.Sedangkan koefisien log_X (B1) sebesar 0.06509 dengan p-valie 0.126 , dimana nilai ini mendekati ambang batas alpha 0.05, sehingga hubungan antara ekspor emas dan GDP kurang signifikan. Nilai R-squared sebesar 21.78% menunjukkan bahwa variabel log_X hanya menjelaskan sebagian kecil variasi dalam log_Y, dan nilai Adjusted R-squared sebesar 13.96% menunjukkan bahwa model kurang fit setelah mempertimbangkan jumlah prediktor. Selain itu, nilai F-statistic sebesar 2.784 dengan p-value 0.1261 juga tidak signifikan, mengindikasikan bahwa model secara keseluruhan tidak menjelaskan hubungan yang kuat antara variabel log_Y dan log_X.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Penelitian ini menemukan adanya hubungan positif antara ekspor emas dan GDP Indonesia pada periode 2012 hingga 2023, di mana setiap peningkatan ekspor emas sebesar 1 unit diestimasi dapat meningkatkan GDP sebesar 0.06509. Namun, hubungan ini kurang signifikan, sehingga ekspor emas memiliki pengaruh yang tidak terlalu kuat terhadap GDP secara keseluruhan. Model regresi yang digunakan menunjukkan bahwa sekitar 21.78% variasi GDP dapat dijelaskan oleh ekspor emas (Multiple R-squared: 0.2178), tetapi adjusted (Adjusted R-squared: 0.1396 ) 13.96% mengindikasikan bahwa kontribusi sebenarnya lebih kecil setelah memperhitungkan kompleksitas model dan jumlah data.</p>
<p>Penelitian ini memiliki keterbatasan, seperti jumlah data yang terbatas (n=12) dan hanya menggunakan satu variabel independen (ekspor emas), sedangkan GDP dipengaruhi oleh banyak faktor lain seperti investasi, konsumsi, impor, dan ekspor komoditas lainnya. Oleh karena itu, penelitian lanjutan disarankan untuk menambahkan variabel independen lain yang relevan, meningkatkan jumlah data, serta menggunakan yang lebih kompleks untuk memperbaiki akurasi model.</p>
<p>Dari temuan ini, dapat disimpulkan bahwa meskipun ekspor emas berkontribusi terhadap GDP, kontribusinya relatif kecil dan belum signifikan secara statistik.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Badan Pusat Statistik. (2024). BPS sebut logam mulia jadi penyumbang ekspor terbesar Maret 2024. Diakses dari Antara News.</p>
<p>Badan Pusat Statistik. (n.d.). Press release. Diakses dari BPS.</p>
<p>CNBC Indonesia. (2022). RI ekspor minyak mentah tapi impor BBM, kok bisa? Diakses dari CNBC Indonesia.</p>
<p>Ekonomi Kementerian Koordinator. (n.d.). Wujudkan transformasi ekonomi mendukung Indonesia emas 2045, Menko Airlangga ungkap keberanian membuat lompatan besar. Diakses dari Kemenko Ekonomi.</p>
<p>Kementerian Perindustrian. (2022). Kemenperin sebut ekspor produk perhiasan capai 3,1 miliar dolar. Diakses dari Antara News.</p>
<p>Kamar Dagang dan Industri Indonesia. (n.d.). Profil ekonomi Indonesia. Diakses dari KADIN.</p>
<p>Magister Manajemen Universitas Toraja. (n.d.). Jurnal Manajemen Ekonomi dan Studi.</p>
<p>Muhammad, A. (2023). Ekspor emas perhiasan paling banyak ke Swiss. Diakses dari Detik Finance.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>